In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
# df.iloc[:, 1:] => : means "all rows", 1: means "columns from position 1 to the end" (everything except the first column). This returns a DataFrame.
# df.iloc[:, 0] => : means "all rows", 0 means "column at position 0" (the first column). This returns a Series — the first column's values.

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""
These lines standardize the features (mean = 0, std = 1), which most ML models (including neural nets) train better with.
scaler = StandardScaler() → creates a scaler object from scikit-learn that will learn how to transform data: z = (x - mean) / std.

X_train = scaler.fit_transform(X_train) → does two things at once:
fit: computes the mean and standard deviation of each column using only the training data.
transform: applies (x - mean) / std to X_train using those computed values, replacing it with the standardized version.

X_test = scaler.transform(X_test) → applies the same mean/std learned from the training set to the test set — it does not re-fit. 
This is important: the test set must be scaled using training statistics, 
otherwise you'd leak information from the test set into your preprocessing (data leakage), and it also wouldn't reflect how the model would behave on truly unseen data in production.

So the rule of thumb: fit_transform on train, transform (only) on test/validation/new data.
"""

"\nThese lines standardize the features (mean = 0, std = 1), which most ML models (including neural nets) train better with.\nscaler = StandardScaler() → creates a scaler object from scikit-learn that will learn how to transform data: z = (x - mean) / std.\n\nX_train = scaler.fit_transform(X_train) → does two things at once:\nfit: computes the mean and standard deviation of each column using only the training data.\ntransform: applies (x - mean) / std to X_train using those computed values, replacing it with the standardized version.\n\nX_test = scaler.transform(X_test) → applies the same mean/std learned from the training set to the test set — it does not re-fit. \nThis is important: the test set must be scaled using training statistics, \notherwise you'd leak information from the test set into your preprocessing (data leakage), and it also wouldn't reflect how the model would behave on truly unseen data in production.\n\nSo the rule of thumb: fit_transform on train, transform (only) on test/validation/new data.\n"

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

"""
Same logic as the StandardScaler. fit_transform makes the labeling of y train and transform the labels inplace
transform on test set uses the labeling done by fit on the train data and transform the test set accordingly.
"""

'\nSame logic as the StandardScaler. fit_transform makes the labeling of y train and transform the labels inplace\ntransform on test set uses the labeling done by fit on the train data and transform the test set accordingly.\n'

In [9]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0])

Numpy arrays to Pytorch tensors

In [10]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [12]:
# Custom Dataset
from torch.utils.data import Dataset, DataLoader

class CustomDataSet(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [13]:
train_dataset = CustomDataSet(X_train_tensor, y_train_tensor)
test_dataset = CustomDataSet(X_test_tensor, y_test_tensor)

In [14]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

Defining The Model

In [15]:
class MySimpleNN(nn.Module): 
    def __init__(self, num_of_features):
        super().__init__()
        self.layer = nn.Linear(num_of_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.layer(features)
        out = self.sigmoid(out)
        
        return out

In [16]:
learning_rate = 0.1 # the alpha - size of the steps the optimizer takes when updating the NN's weights to minimize errors
epochs = 25 # each epoch is one complete pass of the entire training dataset through the neural network. 
#Because a network cannnot find all underlying patterns in a single pass, it requires multiple epochs to analyze and refine its weights

In [17]:
loss_function = nn.BCELoss()

Training Pipeline

#### The torch.optim Module
`torch.optim` is a module in Pytorch that provides a variety of optimization algorithms used to update the parameters of our model during training.
It includes common optimizers like Stochastic Gradient Descent (SGD), Adam, RMSprop, and many more.
It handles weight updates efficiently, including additional features like learning rate scheduling and weight decay (regularization)

##### The model.parameters()
The `model.parameters()` method in PyTorch retrieves an iterator over all the trainable parameters (weights and biases) in a model. These parameters are instances of `torch.nn.Parameter` and include:
- **Weights:** The weight matrices of layers like nn.Linear, nn.Conv2d, etc.
- **Biases:** The bias terms of layers (if they exist).

The optimizer uses these parameters to compute gradients and update them during training

In [24]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# training model in a loop
for epoch in range(epochs):    
    for batch_features, batch_labels in train_loader:
        
        # forward pass
        y_pred = model(batch_features)
        print(y_pred)

        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))
        # print(f"Epoch: {epoch}, loss: {loss}")

        # clearing gradients, if any, before backward pass is a good strategy
        optimizer.zero_grad()

        # backward pass
        loss.backward()
        
        # Using optim method - parameter update
        optimizer.step()
        
        # print loss in each epoch
        print(f"Loss: {loss.item()}, Epoch: {epoch + 1}")

tensor([[0.5837],
        [0.4405],
        [0.5435],
        [0.3241],
        [0.5310],
        [0.4855],
        [0.6275],
        [0.6264],
        [0.5185],
        [0.6053],
        [0.3882],
        [0.5861],
        [0.4817],
        [0.5004],
        [0.5266],
        [0.4705],
        [0.5365],
        [0.4429],
        [0.6320],
        [0.5048],
        [0.4721],
        [0.3656],
        [0.3139],
        [0.5341],
        [0.3627],
        [0.5480],
        [0.6142],
        [0.6104],
        [0.5672],
        [0.5595],
        [0.5002],
        [0.4627]], grad_fn=<SigmoidBackward0>)
Loss: 0.6989942789077759, Epoch: 1
tensor([[0.4088],
        [0.3793],
        [0.5047],
        [0.7489],
        [0.5073],
        [0.5250],
        [0.3500],
        [0.6628],
        [0.5835],
        [0.7184],
        [0.6018],
        [0.5447],
        [0.4446],
        [0.3763],
        [0.8524],
        [0.6042],
        [0.4619],
        [0.2822],
        [0.4008],
        [0.4711],
        [0.5994],
        [0.5994],
        [0.6612],
        [0.5020],
        [0.5525],
        [0.4949],
        [0.3826],
        [0.4246],
        [0.5012],
        [0.2710],
        [0.4839],
        [0.9754]], grad_fn=<SigmoidBackward0>)
Loss: 0.5289528369903564, Epoch: 1
tensor([[0.3438],
        [0.4844],
        [0.1788],
        [0.2992],
        [0.2961],
        [0.4103],
        [0.3605],
        [0.1646],
        [0.2670],
        [0.6230],
        [0.2353],
        [0.4132],
        [0.6457],
        [0.4786],
        [0.5952],
        [0.6010],
        [0.5120],
        [0.3564],
        [0.3390],
        [0.7332],
        [0.3907],
        [0.6782],
        [0.3687],
        [0.2532],
        [0.3211],
        [0.4664],
        [0.3914],
        [0.5595],
        [0.6376],
        [0.3846],
        [0.7497],
        [0.3224]], grad_fn=<SigmoidBackward0>)
Loss: 0.44007769227027893, Epoch: 1
tensor([[0.1700],
        [0.8669],
        [0.7954],
        [0.2275],
        [0.2705],
        [0.2762],
        [0.7476],
        [0.2145],
        [0.5161],
        [0.2088],
        [0.2848],
        [0.3245],
        [0.8212],
        [0.5324],
        [0.4270],
        [0.4898],
        [0.8955],
        [0.2192],
        [0.4449],
        [0.3457],
        [0.7217],
        [0.4375],
        [0.3731],
        [0.2041],
        [0.2464],
        [0.2334],
        [0.4558],
        [0.5150],
        [0.4204],
        [0.4936],
        [0.2417],
        [0.9734]], grad_fn=<SigmoidBackward0>)
Loss: 0.3832778036594391, Epoch: 1
tensor([[0.4503],
        [0.2494],
        [0.3239],
        [0.1375],
        [0.9408],
        [0.1845],
        [0.2792],
        [0.3504],
        [0.2503],
        [0.2792],
        [0.3521],
        [0.8710],
        [0.0841],
        [0.9619],
        [0.2574],
        [0.5318],
        [0.2157],
        [0.2810],
        [0.5403],
        [0.3305],
        [0.7731],
        [0.2031],
        [0.4681],
        [0.3424],
        [0.5094],
        [0.3289],
        [0.9727],
        [0.1441],
        [0.7312],
        [0.5185],
        [0.8891],
        [0.1130]], grad_fn=<SigmoidBackward0>)
Loss: 0.3576835095882416, Epoch: 1
tensor([[0.7609],
        [0.3521],
        [0.0957],
        [0.3483],
        [0.5181],
        [0.5298],
        [0.9501],
        [0.0908],
        [0.8130],
        [0.1788],
        [0.3160],
        [0.3537],
        [0.9890],
        [0.2426],
        [0.0750],
        [0.0698],
        [0.9646],
        [0.4709],
        [0.2147],
        [0.2406],
        [0.1060],
        [0.2512],
        [0.1510],
        [0.2244],
        [0.3133],
        [0.8923],
        [0.5189],
        [0.9113],
        [0.2052],
        [0.9890],
        [0.5851],
        [0.9718]], grad_fn=<SigmoidBackward0>)
Loss: 0.28484979271888733, Epoch: 1
tensor([[0.2258],
        [0.9819],
        [0.7971],
        [0.8957],
        [0.9003],
        [0.9145],
        [0.8012],
        [0.3189],
        [0.9246],
        [0.5175],
        [0.1126],
        [0.9464],
        [0.0924],
        [0.8046],
        [0.2815],
        [0.1466],
        [0.4238],
        [0.4979],
        [0.9298],
        [0.4051],
        [0.1981],
        [0.4272],
        [0.1822],
        [0.2169],
        [0.1206],
        [0.8085],
        [0.1703],
        [0.3558],
        [0.8228],
        [0.2721],
        [0.5703],
        [0.3627]], grad_fn=<SigmoidBackward0>)
Loss: 0.28909817337989807, Epoch: 1
tensor([[0.1359],
        [0.9428],
        [0.5583],
        [0.0850],
        [0.1896],
        [0.8227],
        [0.2151],
        [0.1527],
        [0.5634],
        [0.2241],
        [0.1122],
        [0.2438],
        [0.3185],
        [0.2232],
        [0.9832],
        [0.8229],
        [0.0296],
        [0.4703],
        [0.8146],
        [0.0941],
        [0.6340],
        [0.2569],
        [0.0761],
        [0.1394],
        [0.7783],
        [0.6316],
        [0.2262],
        [0.2193],
        [0.3436],
        [0.0858],
        [0.6429],
        [0.8699]], grad_fn=<SigmoidBackward0>)
Loss: 0.3489649295806885, Epoch: 1
tensor([[0.4507],
        [0.8861],
        [0.1130],
        [0.1479],
        [0.1173],
        [0.1504],
        [0.1592],
        [0.4452],
        [0.4180],
        [0.2737],
        [0.7337],
        [0.9538],
        [0.1197],
        [0.8225],
        [0.8630],
        [0.8371],
        [0.7936],
        [0.1289],
        [0.7831],
        [0.7136],
        [0.9959],
        [0.1020],
        [0.3537],
        [0.0585],
        [0.3426],
        [0.3028],
        [0.1207],
        [0.1646],
        [0.8321],
        [0.8367],
        [0.8564],
        [0.2390]], grad_fn=<SigmoidBackward0>)
Loss: 0.2605524957180023, Epoch: 1
tensor([[0.1186],
        [0.0590],
        [0.6596],
        [0.2408],
        [0.1835],
        [0.3918],
        [0.0796],
        [0.8786],
        [0.2504],
        [0.1827],
        [0.2108],
        [0.9566],
        [0.2140],
        [0.9683],
        [0.5842],
        [0.1220],
        [0.4329],
        [0.2923],
        [0.7360],
        [0.0994],
        [0.8772],
        [0.7280],
        [0.8157],
        [0.9701],
        [0.9782],
        [0.9170],
        [0.7221],
        [0.8666],
        [0.9948],
        [0.9769],
        [0.6191],
        [0.2197]], grad_fn=<SigmoidBackward0>)
Loss: 0.35314488410949707, Epoch: 1
tensor([[0.9915],
        [0.0876],
        [0.9941],
        [0.9587],
        [0.1462],
        [0.1961],
        [0.1913],
        [0.2443],
        [0.1790],
        [0.6627],
        [0.1534],
        [0.0869],
        [0.4721],
        [0.9554],
        [0.2429],
        [0.6298],
        [0.0918],
        [0.2183],
        [0.3029],
        [0.6743],
        [0.0973],
        [0.1461],
        [0.1208],
        [0.0624],
        [0.1297],
        [0.3667],
        [0.1306],
        [0.2626],
        [0.1715],
        [0.0618],
        [0.0858],
        [0.9102]], grad_fn=<SigmoidBackward0>)
Loss: 0.19798104465007782, Epoch: 1
tensor([[0.6208],
        [0.0993],
        [0.1267],
        [0.7532],
        [0.1279],
        [0.9029],
        [0.7653],
        [0.6711],
        [0.1376],
        [0.4199],
        [0.9717],
        [0.4837],
        [0.8775],
        [0.1887],
        [0.1255],
        [0.7929],
        [0.9713],
        [0.9997],
        [0.1348],
        [0.0548],
        [0.0953],
        [0.1366],
        [0.9648],
        [0.6636],
        [0.7580],
        [0.2309],
        [0.2123],
        [0.1435],
        [0.8963],
        [0.3036],
        [0.1101],
        [0.3940]], grad_fn=<SigmoidBackward0>)
Loss: 0.29430660605430603, Epoch: 1
tensor([[0.3105],
        [0.2580],
        [0.1184],
        [0.8061],
        [0.4662],
        [0.0632],
        [0.9988],
        [0.3843],
        [0.0677],
        [0.0407],
        [0.9719],
        [0.6060],
        [0.0566],
        [0.1161],
        [0.2676],
        [0.9194],
        [0.2502],
        [0.9807],
        [0.0636],
        [0.3805],
        [0.9107],
        [0.1641],
        [0.9764],
        [0.9911],
        [0.1259],
        [0.6845],
        [0.6242],
        [0.9996],
        [0.9684],
        [0.7870],
        [0.1926],
        [0.2719]], grad_fn=<SigmoidBackward0>)
Loss: 0.21868129074573517, Epoch: 1
tensor([[0.0548],
        [0.1302],
        [0.1853],
        [0.2216],
        [0.1704],
        [0.1578],
        [0.0737],
        [0.3503],
        [0.0899],
        [0.2134],
        [0.7409],
        [0.9203],
        [0.8765],
        [0.9481],
        [0.9446],
        [0.9495],
        [0.1174],
        [0.9963],
        [0.4332],
        [0.4657],
        [0.9427],
        [0.1116],
        [0.9884],
        [0.9781],
        [0.1306],
        [0.4228],
        [0.1973],
        [0.1787],
        [0.0347],
        [0.8757],
        [0.9826],
        [0.7526]], grad_fn=<SigmoidBackward0>)
Loss: 0.23746059834957123, Epoch: 1
tensor([[0.5006],
        [0.9164],
        [0.0936],
        [0.9344],
        [0.1753],
        [0.1577],
        [0.6262]], grad_fn=<SigmoidBackward0>)
Loss: 0.25431594252586365, Epoch: 1
tensor([[0.0716],
        [0.7134],
        [0.1062],
        [0.0911],
        [0.9011],
        [0.0855],
        [0.1655],
        [0.0466],
        [0.0580],
        [0.7587],
        [0.4741],
        [0.0624],
        [0.3826],
        [0.1977],
        [0.2191],
        [0.7926],
        [0.1955],
        [0.9794],
        [0.8677],
        [0.0923],
        [0.0968],
        [0.6192],
        [0.4331],
        [0.1047],
        [0.6362],
        [0.3856],
        [0.4509],
        [0.0333],
        [0.0932],
        [0.0831],
        [0.0551],
        [0.7015]], grad_fn=<SigmoidBackward0>)
Loss: 0.22737307846546173, Epoch: 2
tensor([[0.1888],
        [0.2644],
        [0.0797],
        [0.4031],
        [0.2415],
        [0.1676],
        [0.0480],
        [0.1034],
        [0.1960],
        [0.0417],
        [0.5351],
        [0.1210],
        [0.2238],
        [0.1633],
        [0.8265],
        [0.9270],
        [0.9831],
        [0.1869],
        [0.2076],
        [0.1276],
        [0.1267],
        [0.2858],
        [0.0634],
        [0.9799],
        [0.1411],
        [0.5793],
        [0.9401],
        [0.0286],
        [0.6713],
        [0.6883],
        [0.1559],
        [0.1044]], grad_fn=<SigmoidBackward0>)
Loss: 0.2806323766708374, Epoch: 2
tensor([[0.9999],
        [0.9313],
        [0.0294],
        [0.6525],
        [0.8643],
        [0.6376],
        [0.8073],
        [0.0721],
        [0.9865],
        [0.1499],
        [0.9422],
        [0.9489],
        [0.7845],
        [0.0406],
        [0.2938],
        [0.9475],
        [0.9831],
        [0.0963],
        [0.0167],
        [0.1521],
        [0.9724],
        [0.7800],
        [0.8102],
        [0.2045],
        [0.0533],
        [0.5060],
        [0.3994],
        [0.1345],
        [0.5347],
        [0.8204],
        [0.0662],
        [0.4777]], grad_fn=<SigmoidBackward0>)
Loss: 0.20230582356452942, Epoch: 2
tensor([[0.8593],
        [0.0813],
        [0.0661],
        [0.1014],
        [0.9642],
        [0.9005],
        [0.1350],
        [0.8965],
        [0.9227],
        [0.0357],
        [0.1294],
        [0.1686],
        [0.6468],
        [0.9170],
        [0.9675],
        [0.4387],
        [0.0940],
        [0.2092],
        [0.0763],
        [0.1495],
        [0.0686],
        [0.1193],
        [0.9999],
        [0.0545],
        [0.7285],
        [0.9833],
        [0.0768],
        [0.5310],
        [0.0291],
        [0.9702],
        [0.5431],
        [0.0181]], grad_fn=<SigmoidBackward0>)
Loss: 0.15449683368206024, Epoch: 2
tensor([[0.0190],
        [0.4294],
        [0.9645],
        [0.9996],
        [0.2744],
        [0.9437],
        [0.1709],
        [0.0447],
        [0.9909],
        [0.6812],
        [0.1065],
        [0.9103],
        [0.1590],
        [0.1502],
        [0.2195],
        [0.7752],
        [0.0404],
        [0.4145],
        [0.3461],
        [0.2015],
        [0.9691],
        [0.0517],
        [0.4348],
        [0.1385],
        [0.1388],
        [0.0851],
        [0.0236],
        [0.4418],
        [0.9018],
        [0.1465],
        [0.0720],
        [0.0281]], grad_fn=<SigmoidBackward0>)
Loss: 0.23049935698509216, Epoch: 2
tensor([[0.9893],
        [0.0679],
        [0.3297],
        [0.1548],
        [0.3655],
        [0.3353],
        [0.9505],
        [0.0527],
        [0.2519],
        [0.8644],
        [0.9544],
        [0.2868],
        [0.1243],
        [0.9835],
        [0.5629],
        [0.9893],
        [0.0673],
        [0.2061],
        [0.4951],
        [0.9612],
        [0.3721],
        [0.8829],
        [0.1988],
        [0.1637],
        [0.0268],
        [0.1965],
        [0.6020],
        [0.0487],
        [0.8409],
        [0.7804],
        [0.0403],
        [0.9955]], grad_fn=<SigmoidBackward0>)
Loss: 0.2147010713815689, Epoch: 2
tensor([[0.1247],
        [0.0851],
        [0.0852],
        [0.1589],
        [0.2830],
        [0.1489],
        [0.9963],
        [0.0261],
        [0.1234],
        [0.9898],
        [0.1986],
        [0.1268],
        [0.1910],
        [0.0331],
        [0.0217],
        [0.0247],
        [0.9139],
        [0.0545],
        [0.6418],
        [0.2508],
        [0.9409],
        [0.9887],
        [0.7573],
        [0.3114],
        [0.6695],
        [0.9968],
        [0.9959],
        [0.1105],
        [0.0892],
        [0.0962],
        [0.7857],
        [0.9505]], grad_fn=<SigmoidBackward0>)
Loss: 0.22606438398361206, Epoch: 2
tensor([[0.0699],
        [0.0469],
        [0.9762],
        [0.6098],
        [0.9993],
        [0.9947],
        [0.0252],
        [0.9907],
        [0.9606],
        [0.9931],
        [0.2772],
        [0.1601],
        [0.1314],
        [0.5204],
        [0.1188],
        [0.1826],
        [0.0945],
        [0.0466],
        [0.0599],
        [0.9780],
        [0.0287],
        [0.9183],
        [0.1754],
        [0.4049],
        [0.9890],
        [0.0414],
        [0.3262],
        [0.9960],
        [0.5122],
        [0.9952],
        [0.0787],
        [0.3107]], grad_fn=<SigmoidBackward0>)
Loss: 0.17231181263923645, Epoch: 2
tensor([[0.0509],
        [0.0486],
        [0.0617],
        [0.2544],
        [0.2118],
        [0.9999],
        [0.0669],
        [0.1309],
        [0.1231],
        [0.0241],
        [0.0560],
        [0.0823],
        [0.0743],
        [0.9416],
        [0.2853],
        [0.8175],
        [0.9984],
        [0.1263],
        [0.9566],
        [0.0973],
        [0.0269],
        [0.0154],
        [0.0069],
        [0.0478],
        [0.3604],
        [0.9369],
        [0.9254],
        [0.9988],
        [0.1199],
        [0.8290],
        [0.0997],
        [0.0558]], grad_fn=<SigmoidBackward0>)
Loss: 0.10411477088928223, Epoch: 2
tensor([[0.0273],
        [0.1257],
        [0.9379],
        [0.9965],
        [0.0628],
        [0.9926],
        [0.0440],
        [0.4480],
        [0.9992],
        [0.1076],
        [0.9469],
        [0.0916],
        [0.0816],
        [0.9658],
        [0.1309],
        [0.0979],
        [0.0441],
        [0.9596],
        [0.2015],
        [0.5621],
        [0.9130],
        [0.8129],
        [0.1560],
        [0.2086],
        [0.1627],
        [0.1226],
        [0.0323],
        [0.5220],
        [0.5989],
        [0.0952],
        [0.6250],
        [0.0295]], grad_fn=<SigmoidBackward0>)
Loss: 0.19295985996723175, Epoch: 2
tensor([[0.0987],
        [0.7599],
        [0.0043],
        [0.9612],
        [0.9828],
        [0.9790],
        [0.0326],
        [0.9308],
        [0.9630],
        [0.9905],
        [0.3889],
        [0.0187],
        [0.1444],
        [0.0173],
        [0.9329],
        [0.9914],
        [0.5313],
        [0.2091],
        [0.1058],
        [0.1109],
        [0.1091],
        [0.0179],
        [0.6982],
        [0.9994],
        [0.1168],
        [0.0708],
        [0.0847],
        [0.7813],
        [0.0471],
        [0.9979],
        [0.0239],
        [0.9669]], grad_fn=<SigmoidBackward0>)
Loss: 0.1127045601606369, Epoch: 2
tensor([[0.1896],
        [0.1783],
        [0.9995],
        [0.4348],
        [0.9820],
        [0.3455],
        [0.0401],
        [0.2788],
        [0.7401],
        [0.1469],
        [0.0142],
        [0.9374],
        [0.0481],
        [0.0692],
        [0.9973],
        [0.9831],
        [0.7957],
        [0.0889],
        [0.0239],
        [0.0349],
        [0.9996],
        [0.0977],
        [0.0421],
        [0.9991],
        [0.0208],
        [0.9910],
        [0.8108],
        [0.1900],
        [0.9999],
        [0.9931],
        [0.6124],
        [0.9999]], grad_fn=<SigmoidBackward0>)
Loss: 0.1702333390712738, Epoch: 2
tensor([[0.9165],
        [0.1097],
        [0.3027],
        [0.5277],
        [0.2281],
        [0.0195],
        [0.1262],
        [0.8459],
        [0.9631],
        [0.9996],
        [0.9386],
        [0.1291],
        [0.9819],
        [0.9995],
        [0.0420],
        [0.0263],
        [0.6090],
        [0.1989],
        [0.1340],
        [0.9346],
        [0.2006],
        [0.0478],
        [0.8916],
        [0.9999],
        [0.7313],
        [0.6789],
        [0.0781],
        [0.1217],
        [0.9645],
        [0.1649],
        [0.9932],
        [0.2668]], grad_fn=<SigmoidBackward0>)
Loss: 0.18358787894248962, Epoch: 2
tensor([[0.0520],
        [0.3744],
        [0.2742],
        [0.0108],
        [0.9289],
        [0.3740],
        [0.9930],
        [0.0358],
        [0.9988],
        [0.0815],
        [0.0868],
        [0.8621],
        [0.9839],
        [0.0369],
        [0.9756],
        [0.2646],
        [0.9994],
        [0.9819],
        [0.0287],
        [0.5654],
        [0.0599],
        [0.0490],
        [0.0698],
        [0.0927],
        [0.9920],
        [0.0270],
        [0.1955],
        [0.1353],
        [0.1155],
        [0.3823],
        [1.0000],
        [0.4746]], grad_fn=<SigmoidBackward0>)
Loss: 0.17109236121177673, Epoch: 2
tensor([[0.0320],
        [0.0227],
        [0.0371],
        [0.0700],
        [0.4560],
        [0.3949],
        [0.0194]], grad_fn=<SigmoidBackward0>)
Loss: 0.1852276474237442, Epoch: 2
tensor([[0.9825],
        [0.0148],
        [0.9681],
        [0.3987],
        [0.0232],
        [0.2768],
        [0.0522],
        [0.0868],
        [0.1326],
        [0.9680],
        [0.2325],
        [0.9674],
        [0.0140],
        [0.0542],
        [0.4860],
        [0.3086],
        [0.1322],
        [0.9646],
        [0.9317],
        [0.0517],
        [0.0133],
        [0.9941],
        [0.0655],
        [0.9529],
        [0.1121],
        [0.9954],
        [0.0178],
        [0.0484],
        [0.1042],
        [0.0611],
        [0.2572],
        [0.0205]], grad_fn=<SigmoidBackward0>)
Loss: 0.15068496763706207, Epoch: 3
tensor([[0.1298],
        [0.9493],
        [0.9369],
        [0.0496],
        [0.9990],
        [0.9694],
        [0.0292],
        [0.0905],
        [0.0658],
        [0.7772],
        [0.8714],
        [0.0570],
        [0.9802],
        [0.7856],
        [0.3085],
        [1.0000],
        [0.1260],
        [0.1593],
        [0.0829],
        [0.8875],
        [0.0624],
        [0.0084],
        [0.0953],
        [0.9756],
        [0.9997],
        [0.9524],
        [0.7124],
        [0.7857],
        [0.4595],
        [0.0470],
        [0.9998],
        [0.6742]], grad_fn=<SigmoidBackward0>)
Loss: 0.13035565614700317, Epoch: 3
tensor([[0.0770],
        [0.1759],
        [0.7082],
        [0.0358],
        [0.9395],
        [0.5513],
        [0.0130],
        [0.1300],
        [0.0094],
        [0.0262],
        [0.8766],
        [0.0454],
        [0.9826],
        [0.0873],
        [0.0487],
        [0.1457],
        [0.9759],
        [0.9038],
        [0.8582],
        [0.1098],
        [0.8402],
        [0.0116],

In [25]:
print(f"Weights: {model.layer.weight}")
print(f"Bias: {model.layer.bias}")

Weights: Parameter containing:
tensor([[ 0.6125,  0.4081,  0.2922,  0.4120,  0.1989, -0.0096,  0.4746,  0.6473,
          0.0172, -0.3129,  0.5601, -0.0201,  0.4864,  0.6377,  0.1003, -0.3280,
         -0.0658,  0.0506, -0.1985, -0.3676,  0.7740,  0.7734,  0.4458,  0.5906,
          0.4710,  0.3100,  0.4649,  0.5916,  0.5530,  0.0798]],
       requires_grad=True)
Bias: Parameter containing:
tensor([-0.2968], requires_grad=True)

In [26]:
# model evaluation with new weight and bias value
model.eval() # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()
        
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)
    
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

Accuracy: 0.9766